# -*- coding: utf-8 -*-
"""CS247A Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12utc5xv3YxWExrWkesAYU2Tc13Of8Ptc
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/CS247A_projects/emg2qwerty

!pip install -r requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/CS247A_projects/emg2qwerty

# Commented out IPython magic to ensure Python compatibility.
# %ls /content/drive/MyDrive/CS247A_projects/emg2qwerty

### optional test - Single-user training ###

# !python -m emg2qwerty.train \
  #user="single_user" \
  #trainer.accelerator=gpu trainer.devices=1 \
  # --multirun

### optional test - training tds_conv_ctc model ###

#!python -m emg2qwerty.train \
  #user=single_user \
  #model=tds_conv_ctc \
  #trainer.accelerator=gpu trainer.devices=1 \
  #trainer.max_epochs=1

# Commented out IPython magic to ensure Python compatibility.
# %%writefile emg2qwerty/lightning_cnn_rnn.py
# # CNN + RNN hybrid for CTC decoding
# from collections.abc import Sequence
# from typing import Any, ClassVar
# 
# import pytorch_lightning as pl
# import torch
# from hydra.utils import instantiate
# from omegaconf import DictConfig
# from torch import nn
# from torchmetrics import MetricCollection
# 
# from emg2qwerty import utils
# from emg2qwerty.charset import charset
# from emg2qwerty.data import LabelData
# from emg2qwerty.metrics import CharacterErrorRates
# from emg2qwerty.modules import SpectrogramNorm
# 
# 
# class CNNRNNCTCModule(pl.LightningModule):
#     """
#     Drop-in replacement for TDSConvCTCModule, reusing the same CTC/decoder/metrics pipeline.
# 
#     Expects inputs in time-first format:
#       inputs: (T, N, bands=2, electrode_channels=16, freq)
#     Outputs:
#       emissions: (T, N, num_classes) log-probs
#     """
#     NUM_BANDS: ClassVar[int] = 2
#     ELECTRODE_CHANNELS: ClassVar[int] = 16
# 
#     def __init__(
#         self,
#         in_features: int,
#         cnn_channels: int,
#         rnn_hidden: int,
#         rnn_layers: int,
#         kernel_size: int,
#         dropout: float,
#         optimizer: DictConfig,
#         lr_scheduler: DictConfig,
#         decoder: DictConfig,
#     ) -> None:
#         super().__init__()
#         self.save_hyperparameters()
# 
#         # Normalization used in baseline
#         self.spec_norm = SpectrogramNorm(channels=self.NUM_BANDS * self.ELECTRODE_CHANNELS)
# 
#         # Temporal CNN over flattened spectral features.
#         # Keep stride=1 so time length stays the same -> emission length logic stays valid.
#         self.cnn = nn.Sequential(
#             nn.Conv1d(in_features, cnn_channels, kernel_size=kernel_size, padding=kernel_size // 2, stride=1),
#             nn.BatchNorm1d(cnn_channels),
#             nn.ReLU(),
#             nn.Dropout(dropout),
# 
#             nn.Conv1d(cnn_channels, cnn_channels, kernel_size=kernel_size, padding=kernel_size // 2, stride=1),
#             nn.BatchNorm1d(cnn_channels),
#             nn.ReLU(),
#             nn.Dropout(dropout),
#         )
# 
#         self.rnn = nn.LSTM(
#             input_size=cnn_channels,
#             hidden_size=rnn_hidden,
#             num_layers=rnn_layers,
#             bidirectional=True,
#             dropout=dropout if rnn_layers > 1 else 0.0,
#         )
# 
#         self.head = nn.Sequential(
#             nn.Linear(2 * rnn_hidden, charset().num_classes),
#             nn.LogSoftmax(dim=-1),
#         )
# 
#         # Loss / decoder / metrics (same as baseline)
#         self.ctc_loss = nn.CTCLoss(blank=charset().null_class)
#         self.decoder = instantiate(decoder)
# 
#         metrics = MetricCollection([CharacterErrorRates()])
#         self.metrics = nn.ModuleDict(
#             {
#                 f"{phase}_metrics": metrics.clone(prefix=f"{phase}/")
#                 for phase in ["train", "val", "test"]
#             }
#         )
# 
#     def forward(self, inputs: torch.Tensor) -> torch.Tensor:
#         # inputs: (T, N, 2, 16, freq)
#         x = self.spec_norm(inputs)
#         T, N = x.shape[0], x.shape[1]
# 
#         # Flatten (2,16,freq) -> feature dim
#         x = x.reshape(T, N, -1)       # (T, N, in_features)
#         x = x.permute(1, 2, 0)        # (N, in_features, T)
# 
#         x = self.cnn(x)               # (N, cnn_channels, T)
#         x = x.permute(2, 0, 1)        # (T, N, cnn_channels)
# 
#         x, _ = self.rnn(x)            # (T, N, 2*rnn_hidden)
#         x = self.head(x)              # (T, N, num_classes)
#         return x
# 
#     def _step(self, phase: str, batch: dict[str, torch.Tensor]) -> torch.Tensor:
#         inputs = batch["inputs"]
#         targets = batch["targets"]
#         input_lengths = batch["input_lengths"]
#         target_lengths = batch["target_lengths"]
#         N = len(input_lengths)
# 
#         emissions = self.forward(inputs)
# 
#         # since we keep time length same, T_diff should be 0 (but keep generic)
#         T_diff = inputs.shape[0] - emissions.shape[0]
#         emission_lengths = input_lengths - T_diff
# 
#         loss = self.ctc_loss(
#             log_probs=emissions,
#             targets=targets.transpose(0, 1),  # (T,N)->(N,T)
#             input_lengths=emission_lengths,
#             target_lengths=target_lengths,
#         )
# 
#         predictions = self.decoder.decode_batch(
#             emissions=emissions.detach().cpu().numpy(),
#             emission_lengths=emission_lengths.detach().cpu().numpy(),
#         )
# 
#         metrics = self.metrics[f"{phase}_metrics"]
#         targets_np = targets.detach().cpu().numpy()
#         target_lengths_np = target_lengths.detach().cpu().numpy()
# 
#         for i in range(N):
#             target = LabelData.from_labels(targets_np[: target_lengths_np[i], i])
#             metrics.update(prediction=predictions[i], target=target)
# 
#         self.log(f"{phase}/loss", loss, batch_size=N, sync_dist=True)
#         return loss
# 
#     def training_step(self, batch, batch_idx):
#         return self._step("train", batch)
# 
#     def validation_step(self, batch, batch_idx):
#         return self._step("val", batch)
# 
#     def test_step(self, batch, batch_idx):
#         return self._step("test", batch)
# 
#     def on_train_epoch_end(self):
#         self.log_dict(self.metrics["train_metrics"].compute(), sync_dist=True)
#         self.metrics["train_metrics"].reset()
# 
#     def on_validation_epoch_end(self):
#         self.log_dict(self.metrics["val_metrics"].compute(), sync_dist=True)
#         self.metrics["val_metrics"].reset()
# 
#     def on_test_epoch_end(self):
#         self.log_dict(self.metrics["test_metrics"].compute(), sync_dist=True)
#         self.metrics["test_metrics"].reset()
# 
#     def configure_optimizers(self) -> dict[str, Any]:
#         return utils.instantiate_optimizer_and_scheduler(
#             self.parameters(),
#             optimizer_config=self.hparams.optimizer,
#             lr_scheduler_config=self.hparams.lr_scheduler,
#         )

content = """# @package _global_

module:
  _target_: emg2qwerty.lightning_cnn_rnn.CNNRNNCTCModule
  in_features: 1056
  cnn_channels: 256
  rnn_hidden: 256
  rnn_layers: 2
  kernel_size: 5
  dropout: 0.3

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]
"""

with open("config/model/cnn_rnn_ctc.yaml", "w") as f:
    f.write(content)

!python -m emg2qwerty.train \
  user=single_user \
  model=cnn_rnn_ctc \
  trainer.accelerator=gpu trainer.devices=1 \
  trainer.max_epochs=10

!python -m emg2qwerty.train \
  user=single_user \
  model=cnn_rnn_ctc \
  trainer.accelerator=gpu trainer.devices=1 \
  trainer.max_epochs=50